# Generated by Django 4.1 on 2024-03-18 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "classroom_id",
                    models.CharField(
                        editable=False, max_length=3, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("semester", models.CharField(max_length=255)),
                ("school", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Snipsheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snipsheet_id",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snipsheets",
                        to="snips.classroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Snip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snip_id", models.CharField(max_length=9)),
                ("student_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "snipsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snips",
                        to="snips.snipsheet",
                    ),
                ),
            ],
        ),
    ]
