# Generated by Django 4.1 on 2024-03-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
