# Generated by Django 4.1 on 2024-03-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snips", "0002_classroom_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="snip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="snipsheet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
